include "base"
include "version"

user.password.bpass.secret = "9qEYN0ThHer1KWLNekA76Q=="

net.site.name = "Chesstory"
net.domain = ${?CHESSTORY_DOMAIN}
net.socket.domains = []
net.asset.base_url = ${?CHESSTORY_URL}
net.base_url = ${?CHESSTORY_URL}
net.email = ${?PUBLIC_CONTACT_EMAIL}
net.ratelimit = ${?ENABLE_RATE_LIMITING}

security.password_reset.secret = ${?PASSWORD_RESET_SECRET}
security.email_confirm.secret = ${?EMAIL_CONFIRM_SECRET}
security.email_change.secret = ${?EMAIL_CHANGE_SECRET}
security.login_token.secret = ${?LOGIN_TOKEN_SECRET}

mongodb.uri = "mongodb://mongodb?appName=chesstory"
redis.uri = "redis://redis"

security.email_confirm.enabled = true

push.web.url = ""
push.web.vapid_public_key = ""

support.links.patreon = ${?SUPPORT_PATREON_URL}
support.links.githubSponsors = ${?SUPPORT_GITHUB_SPONSORS_URL}
support.links.buyMeACoffee = ${?SUPPORT_BMC_URL}

hcaptcha.enabled = ${?HCAPTCHA_ENABLED}
hcaptcha.public.sitekey = ${?HCAPTCHA_SITEKEY}
hcaptcha.secret = ${?HCAPTCHA_SECRET}

explorer.endpoint = ${?EXPLORER_API_BASE}
explorer.internal_endpoint = ${?EXPLORER_API_BASE}
explorer.tablebase_endpoint = ${?TABLEBASE_API_BASE}

external.import.lichess.api_base = ${?LICHESS_IMPORT_API_BASE}
external.import.lichess.web_base = ${?LICHESS_WEB_BASE}
external.import.chesscom.api_base = ${?CHESSCOM_API_BASE}
